### ISSUE TITLE
burpsuite_pro_v2022.12.7 issue

### ISSUE THREAD

**Issue by irsdl** [CoreyD97/Burp-Montoya-Utilities#1]
Here is the error message:
```
java.lang.AbstractMethodError: Receiver class com.coreyd97.BurpExtenderUtilities.ProjectSettingStore does not define or inherit an implementation of the resolved method 'abstract burp.api.montoya.http.message.requests.HttpRequest httpRequest()' of interface burp.api.montoya.http.message.HttpRequestResponse.
```

burpsuite_pro_v2022.12.7.jar
jdk-17.0.5

**Comment by CoreyD97** [comment]
Versions of the Montoya API included in Burp prior to [2023.1](https://portswigger.net/burp/releases/professional-community-2023-1) were a pre-release of the Montoya API. 

Since there were significant changes in Montoya v1.0, there's no realistic way to make this backwards compatible unfortunately.
